export const permissions = [
  "message_compose",
  "message_view_inbox",
  "message_view_sent",
  "message_view_drafts",
  "message_view_attachments_logs",
  "message_forward_update",
  "message_destroy_update",
  "message_release_update",
  "connections_send_request",
  "connections_view_list",
  "connections_view_requests",
  "connections_approve_requests",
  "users_view_list",
];